### ISSUE TITLE
testsuite fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [rudymatela/leancheck-instances#3]
For Stackage Nightly with ghc-9.10.2

```
       Building test suite 'text-' for leancheck-instances-0.0.5...                                                                 
       [1 of 1] Compiling Main                                                                                                      
       /home/curators/work/unpack-dir/unpacked/leancheck-instances-0.0.5-57fc1f3239b31d9d4317a5c01849cf4cd02ca42d7e754cf4a4b4a949c25
b0d0d/test/text.hs:15:38: error: [GHC-87543]                                                                                        
           Ambiguous occurrence ‘show’.                                                                                             
           It could refer to                                                                                                        
              either ‘Data.Text.show’,                                                                                              
                     imported from ‘Data.Text’ at test/text.hs:5:1-16,                                                              
                  or ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at test/text.hs:9:1-54                                                                 
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’).                                         
          |                                                                                                                         
       15 |   is -> putStrLn ("Failed tests:" ++ show is) >> exitFailure                                                            
          |                                      ^^^^
```

**Comment by rudymatela** [comment]
Thanks for reporting.

The issue is fixed on the main branch, I just need to make a new release.  I will do so soon.

**Comment by rudymatela** [comment]
Version 0.0.8 is released.  I think the expected test failure can now be safely removed from Hackage:

https://github.com/commercialhaskell/stackage/pull/7749

Again thanks for reporting.  This is always helpful.  😁
